apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-server
  name: grpc-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grpc-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grpc-server
    spec:
      containers:
      - image: clarechu/grpc-server:v1.0
        imagePullPolicy: Always
        name: grpc-server
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-server
  name: grpc-server
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: grpc-7575
      port: 7575
      protocol: TCP
      targetPort: 7575
  selector:
    app: grpc-server
  sessionAffinity: None
  type: NodePort
