---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: {{ .Values.hub }}{{ .Values.imageName }}:{{ .Values.tag }}
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: {{ .Values.nfs.server }} ## 指定自己nfs服务器地址
            - name: NFS_PATH
              value: {{ .Values.nfs.path }}  ## nfs服务器共享的目录
      volumes:
        - name: nfs-client-root
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.path }}

---
