---

apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: grpc-client
    version: v1
  name: grpc-client-v1
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grpc-client
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grpc-client
        version: v1
    spec:
      containers:
        - args:
            - grpc-client
            - --addr=grpc-server
          image: clarechu/grpc-client:v1.0
          imagePullPolicy: Always
          name: grpc-client
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---