---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-client
    service: grpc-client
  name: grpc-client
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: grpc
      port: 7575
      protocol: TCP
      targetPort: 7575
  selector:
    app: grpc-client
  sessionAffinity: None
  type: NodePort

---