# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullname: filebeat
imagePullPolicy: IfNotPresent
filebeat:
  namespace: kube-system
  enabled: false

global:
  version: 7.16.1
