# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullname: filebeat
imagePullPolicy: IfNotPresent
namespace: kube-system
enabled: true

global:
  version: 7.16.1
