apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: details
    version: v1
  name: details-v1
  namespace: demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: details
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      containers:
        - image: registry.cn-shenzhen.aliyuncs.com/solar-mesh/examples-bookinfo-details-v1:1.15.0
          imagePullPolicy: IfNotPresent
          name: details
          ports:
            - containerPort: 9080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bookinfo-details
      serviceAccountName: bookinfo-details
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: details
    service: details
  name: details
  namespace: demo
spec:
  clusterIP: 10.70.125.117
  ports:
    - name: http
      port: 9080
      protocol: TCP
      targetPort: 9080
  selector:
    app: details
  sessionAffinity: None
  type: ClusterIP