// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package proto // import "github.com/ClareChu/proxy-istio-demo/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DemoRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoRequest) Reset()         { *m = DemoRequest{} }
func (m *DemoRequest) String() string { return proto.CompactTextString(m) }
func (*DemoRequest) ProtoMessage()    {}
func (*DemoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_5aad2f373aee0460, []int{0}
}
func (m *DemoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoRequest.Unmarshal(m, b)
}
func (m *DemoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoRequest.Marshal(b, m, deterministic)
}
func (dst *DemoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoRequest.Merge(dst, src)
}
func (m *DemoRequest) XXX_Size() int {
	return xxx_messageInfo_DemoRequest.Size(m)
}
func (m *DemoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DemoRequest proto.InternalMessageInfo

func (m *DemoRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DemoResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoResponse) Reset()         { *m = DemoResponse{} }
func (m *DemoResponse) String() string { return proto.CompactTextString(m) }
func (*DemoResponse) ProtoMessage()    {}
func (*DemoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_5aad2f373aee0460, []int{1}
}
func (m *DemoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoResponse.Unmarshal(m, b)
}
func (m *DemoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoResponse.Marshal(b, m, deterministic)
}
func (dst *DemoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoResponse.Merge(dst, src)
}
func (m *DemoResponse) XXX_Size() int {
	return xxx_messageInfo_DemoResponse.Size(m)
}
func (m *DemoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DemoResponse proto.InternalMessageInfo

func (m *DemoResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DemoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DemoResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*DemoRequest)(nil), "v1.DemoRequest")
	proto.RegisterType((*DemoResponse)(nil), "v1.DemoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DemoInterfaceClient is the client API for DemoInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DemoInterfaceClient interface {
	Get(ctx context.Context, in *DemoRequest, opts ...grpc.CallOption) (*DemoResponse, error)
}

type demoInterfaceClient struct {
	cc *grpc.ClientConn
}

func NewDemoInterfaceClient(cc *grpc.ClientConn) DemoInterfaceClient {
	return &demoInterfaceClient{cc}
}

func (c *demoInterfaceClient) Get(ctx context.Context, in *DemoRequest, opts ...grpc.CallOption) (*DemoResponse, error) {
	out := new(DemoResponse)
	err := c.cc.Invoke(ctx, "/v1.DemoInterface/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoInterfaceServer is the server API for DemoInterface service.
type DemoInterfaceServer interface {
	Get(context.Context, *DemoRequest) (*DemoResponse, error)
}

func RegisterDemoInterfaceServer(s *grpc.Server, srv DemoInterfaceServer) {
	s.RegisterService(&_DemoInterface_serviceDesc, srv)
}

func _DemoInterface_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoInterfaceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DemoInterface/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoInterfaceServer).Get(ctx, req.(*DemoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DemoInterface_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.DemoInterface",
	HandlerType: (*DemoInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _DemoInterface_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_demo_5aad2f373aee0460) }

var fileDescriptor_demo_5aad2f373aee0460 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0xcd, 0xcd,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x54, 0x52, 0xe7, 0xe2, 0x76, 0x49,
	0xcd, 0xcd, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0xcf, 0x4d, 0x2d,
	0x2e, 0x4e, 0x4c, 0x4f, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x95, 0x02, 0xb8,
	0x78, 0x20, 0x0a, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x84, 0xb8, 0x58, 0x92, 0xf3, 0x53,
	0x20, 0xca, 0x58, 0x83, 0xc0, 0x6c, 0x64, 0xdd, 0x4c, 0x28, 0xba, 0x41, 0xaa, 0x53, 0x12, 0x4b,
	0x12, 0x25, 0x98, 0xc1, 0xc2, 0x60, 0xb6, 0x91, 0x35, 0x17, 0x2f, 0xc8, 0x44, 0xcf, 0xbc, 0x92,
	0xd4, 0xa2, 0xb4, 0xc4, 0xe4, 0x54, 0x21, 0x2d, 0x2e, 0x66, 0xf7, 0xd4, 0x12, 0x21, 0x7e, 0xbd,
	0x32, 0x43, 0x3d, 0x24, 0x47, 0x49, 0x09, 0x20, 0x04, 0x20, 0x96, 0x2b, 0x31, 0x38, 0xe9, 0x44,
	0x69, 0xa5, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x3b, 0xe7, 0x24, 0x16,
	0xa5, 0x3a, 0x67, 0x94, 0xea, 0x17, 0x14, 0xe5, 0x57, 0x54, 0xea, 0x66, 0x16, 0x97, 0x64, 0xe6,
	0xeb, 0x82, 0x7c, 0xaa, 0x0f, 0xf6, 0x69, 0x12, 0x1b, 0x98, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xf4, 0xb9, 0xc2, 0x29, 0xfe, 0x00, 0x00, 0x00,
}
