// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mail.proto

package proto // import "github.com/ClareChu/proxy-istio-demo/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MailRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailRequest) Reset()         { *m = MailRequest{} }
func (m *MailRequest) String() string { return proto.CompactTextString(m) }
func (*MailRequest) ProtoMessage()    {}
func (*MailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mail_8bf8483ba063eb26, []int{0}
}
func (m *MailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailRequest.Unmarshal(m, b)
}
func (m *MailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailRequest.Marshal(b, m, deterministic)
}
func (dst *MailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailRequest.Merge(dst, src)
}
func (m *MailRequest) XXX_Size() int {
	return xxx_messageInfo_MailRequest.Size(m)
}
func (m *MailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MailRequest proto.InternalMessageInfo

func (m *MailRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MailResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailResponse) Reset()         { *m = MailResponse{} }
func (m *MailResponse) String() string { return proto.CompactTextString(m) }
func (*MailResponse) ProtoMessage()    {}
func (*MailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mail_8bf8483ba063eb26, []int{1}
}
func (m *MailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailResponse.Unmarshal(m, b)
}
func (m *MailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailResponse.Marshal(b, m, deterministic)
}
func (dst *MailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailResponse.Merge(dst, src)
}
func (m *MailResponse) XXX_Size() int {
	return xxx_messageInfo_MailResponse.Size(m)
}
func (m *MailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MailResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MailRequest)(nil), "v1.MailRequest")
	proto.RegisterType((*MailResponse)(nil), "v1.MailResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MailInterfaceClient is the client API for MailInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MailInterfaceClient interface {
	Get(ctx context.Context, in *MailRequest, opts ...grpc.CallOption) (*MailResponse, error)
}

type mailInterfaceClient struct {
	cc *grpc.ClientConn
}

func NewMailInterfaceClient(cc *grpc.ClientConn) MailInterfaceClient {
	return &mailInterfaceClient{cc}
}

func (c *mailInterfaceClient) Get(ctx context.Context, in *MailRequest, opts ...grpc.CallOption) (*MailResponse, error) {
	out := new(MailResponse)
	err := c.cc.Invoke(ctx, "/v1.MailInterface/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailInterfaceServer is the server API for MailInterface service.
type MailInterfaceServer interface {
	Get(context.Context, *MailRequest) (*MailResponse, error)
}

func RegisterMailInterfaceServer(s *grpc.Server, srv MailInterfaceServer) {
	s.RegisterService(&_MailInterface_serviceDesc, srv)
}

func _MailInterface_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailInterfaceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MailInterface/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailInterfaceServer).Get(ctx, req.(*MailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MailInterface_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.MailInterface",
	HandlerType: (*MailInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _MailInterface_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mail.proto",
}

func init() { proto.RegisterFile("mail.proto", fileDescriptor_mail_8bf8483ba063eb26) }

var fileDescriptor_mail_8bf8483ba063eb26 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0xcc, 0xcc,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x54, 0x52, 0xe7, 0xe2, 0xf6, 0x4d,
	0xcc, 0xcc, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0xcf, 0x4d, 0x2d,
	0x2e, 0x4e, 0x4c, 0x4f, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x95, 0xf8, 0xb8,
	0x78, 0x20, 0x0a, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x8d, 0xac, 0xb9, 0x78, 0x41, 0x7c, 0xcf,
	0xbc, 0x92, 0xd4, 0xa2, 0xb4, 0xc4, 0xe4, 0x54, 0x21, 0x2d, 0x2e, 0x66, 0xf7, 0xd4, 0x12, 0x21,
	0x7e, 0xbd, 0x32, 0x43, 0x3d, 0x24, 0x23, 0xa5, 0x04, 0x10, 0x02, 0x10, 0xad, 0x4a, 0x0c, 0x4e,
	0x3a, 0x51, 0x5a, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0xce, 0x39,
	0x89, 0x45, 0xa9, 0xce, 0x19, 0xa5, 0xfa, 0x05, 0x45, 0xf9, 0x15, 0x95, 0xba, 0x99, 0xc5, 0x25,
	0x99, 0xf9, 0xba, 0x29, 0xa9, 0xb9, 0xf9, 0xfa, 0x60, 0x77, 0x26, 0xb1, 0x81, 0x29, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x33, 0x20, 0x36, 0x73, 0xbc, 0x00, 0x00, 0x00,
}
