# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: elasticsearch
nameOverride: elasticsearch
clusterName: elasticsearch-cluster
nodeGroup:


replicas: 1

volumes:
  type: hostPath

global:
  version: 7.16.1

