# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
enabled: true

fullnameOverride: elasticsearch
nameOverride: elasticsearch
clusterName: elasticsearch-cluster
nodeGroup:



replicas: 1

volumes:
  type: emptyDir

java:
  ops: -Xms512m -Xmx512m

global:
  version: 7.16.1
  hub: docker.elastic.co/elasticsearch/

