# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
elasticsearch:
  enabled: true
fullnameOverride: elasticsearch
nameOverride: elasticsearch
clusterName: elasticsearch-cluster
nodeGroup:


replicas: 1

volumes:
  type: hostPath
java:
  ops: -Xms512m -Xmx512m

global:
  version: 7.16.1
  hub: docker.elastic.co/elasticsearch/

