{{- if .Values.kibana.enabled }}
apiVersion: v1
data:
  kibana.yml: |-
    # Default Kibana configuration for docker target
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: [ {{ template "kibana.elasticsearch.hosts" . }} ]
    xpack.monitoring.ui.container.elasticsearch.enabled: true
kind: ConfigMap
metadata:
  name: kibana-cm
  labels:
    version: {{ .Values.global.version }}
    {{- end }}