{{- if .Values.kibana.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
    version: {{ .Values.global.version }}
  name: kibana
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kibana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - image: {{ .Values.global.hub }}{{ .Values.fullname }}:{{ .Values.global.version }}
          imagePullPolicy: IfNotPresent
          name: kibana
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/kibana/config
              name: kibana-cm
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: kibana-cm
          name: kibana-cm
          {{- end }}