{{- if .Values.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
    version: {{ .Values.global.version }}
  name: kibana
spec:
  ports:
    - name: http-5601
      port: 5601
      protocol: TCP
      targetPort: 5601
  selector:
    app: kibana
  sessionAffinity: None
  type: ClusterIP
---
  {{- end }}